### PR TITLE
Readme added to QuantEst

### PR DESCRIPTION
**Pull request by HeySue**
QuantEst folder reconstructed as well.
Please let me know if the structure of my repo is still unclear.

### CODE REVIEW

**Comment by chengsoonong** [comment]
Try to not commit outputs of computation (e.g. plots). Assume that I can run the notebooks (and of course provide instructions on how I should set up to run the notebooks). 

Keeping track of all python packages (i.e. import statements) would be useful in the long run. This is usually done as a requirements.txt file, but I suggest adding a list of packages to your README.

**Comment by HeySue** [comment]
Okay I'll remove all pdf and image files and have a look at the packages.

Can you please have a look of the loss_smoothing_fail.pdf? I think that file should be removed from the repo but I'm not sure.
________________________________

**Comment by chengsoonong** [comment]
Keep all results. Success or failure.

**Comment by HeySue** [comment]
Generated .png files removed from repo

**Pull request merged**
